#!/bin/bash
cd ~/app-root/runtime/deploy
pwd >> ${OPENSHIFT_LOG_DIR}/ticktock.log

if [ ! -f $OPENSHIFT_DATA_DIR/last_run ]; then
  touch $OPENSHIFT_DATA_DIR/last_run
fi
if [[ $(find $OPENSHIFT_DATA_DIR/last_run -mmin +4) ]]; then #run every 5 mins
  cd ~/
#  rm -f $OPENSHIFT_DATA_DIR/last_run
#  touch $OPENSHIFT_DATA_DIR/last_run
#  date >> ${OPENSHIFT_LOG_DIR}/ticktock.log
#  rm -rf delegatescampaign
#  git clone https://github.com/madeofpeople/delegatescampaign
#  cd delegatescampaign
#  npm install
#  npm build
#  npm run gh-deploy
fi
